fb_oauth_token = 'access_token=<oauthtoken>'
fb_group_id = '<groupid>'
fb_graph_url = 'https://graph.facebook.com'
wiki_url = 'http://<site>/<?path>/doku.php'
wiki_user = '<user>'
wiki_pw = '<password>'
wiki_prefix = '<group>Feed_'
